// Default fallback data for standalone static client deployments (e.g. Netlify static hosting)
export const fallbackProjects = [
  {
    id: 'proj_primegold',
    name: 'Prime Gold Resources',
    domain: 'prime-gold-resources.vercel.app',
    url: 'https://prime-gold-resources.vercel.app',
    logo: '/images/prime_gold_logo.jpg',
    banner: '/images/prime_gold_banner.jpg',
    status: 'PAYING',
    category: 'Class "Premium" (TOP Choices)',
    rating: 5.0,
    reviewsCount: 3,
    votes: { excellent: 3, good: 0, average: 0, bad: 0, veryBad: 0 },
    ourInvestment: 2200,
    minDeposit: 20,
    maxDeposit: 2500,
    roi: 20.00,
    duration: '5% to 20% total profit (1 - 7 days)',
    withdrawalType: 'Instant',
    referralPercent: '5% - 2% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-08-29',
    monitoredDays: 9,
    monitorsCount: 1,
    ssl: '256-Bit Encrypted (EV SSL)',
    hosting: 'Vercel / Cloudflare',
    processors: ['Bitcoin', 'Ethereum', 'USDT TRC20', 'USDT BEP20'],
    telegram: 'https://t.me/primegoldresources',
    description: 'Prime Gold Resources is a registered, regulated cryptocurrency cloud mining and algorithmic investment firm headquartered in the United Kingdom, delivering steady daily capital growth and automated liquid contracts to worldwide private investors.'
  },
  {
    id: 'proj_auradiamond',
    name: 'Aura Diamond Holdings',
    domain: 'auradiamondholdings.com',
    url: 'https://auradiamondholdings.com',
    logo: '/images/aura_diamond_logo.jpg',
    banner: '/images/aura_diamond_banner.jpg',
    status: 'PAYING',
    category: 'Class "Premium" (TOP Choices)',
    rating: 4.9,
    reviewsCount: 8,
    votes: { excellent: 8, good: 0, average: 0, bad: 0, veryBad: 0 },
    ourInvestment: 3500,
    minDeposit: 50,
    maxDeposit: 50000,
    roi: 18.50,
    duration: '2.5% to 4.5% daily (30 days)',
    withdrawalType: 'Instant',
    referralPercent: '7% - 3% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-08-20',
    monitoredDays: 17,
    monitorsCount: 4,
    ssl: 'DigiCert High Assurance EV CA-1',
    hosting: 'Dedicated Server (DDoS-Guard)',
    processors: ['Bitcoin', 'Ethereum', 'USDT TRC20', 'TRON', 'Litecoin'],
    telegram: 'https://t.me/auradiamond',
    description: 'Aura Diamond Holdings specializes in rough diamond acquisition, certified gemological cutting, and high-frequency arbitrage trading.'
  },
  {
    id: 'proj_1',
    name: 'Quantum Wealth Matrix',
    domain: 'quantumwealth.io',
    url: 'https://quantumwealth.io',
    logo: '/images/project1.png',
    status: 'PAYING',
    category: 'Class "Premium" (TOP Choices)',
    rating: 4.9,
    reviewsCount: 142,
    votes: { excellent: 128, good: 11, average: 2, bad: 1, veryBad: 0 },
    ourInvestment: 1200,
    minDeposit: 25,
    maxDeposit: 100000,
    roi: 3.5,
    duration: '3.5% Daily for 30 Days (Principal Back)',
    withdrawalType: 'Instant',
    referralPercent: '7% - 2% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-07-10',
    monitoredDays: 58,
    monitorsCount: 12,
    ssl: 'Cloudflare Inc ECC CA-3 (Valid)',
    hosting: 'DDoS-Guard.net (Protected)',
    processors: ['Bitcoin', 'Ethereum', 'USDT TRC20', 'Litecoin', 'Tron'],
    description: 'Quantum algorithmic high-frequency cryptocurrency arbitrage and decentralized yield farming liquidity provider.'
  },
  {
    id: 'proj_2',
    name: 'Nexus Alpha Yield',
    domain: 'nexus-yield.net',
    url: 'https://nexus-yield.net',
    logo: '/images/project2.png',
    status: 'PAYING',
    category: 'Class "A" (Top Performer)',
    rating: 4.8,
    reviewsCount: 89,
    votes: { excellent: 75, good: 10, average: 3, bad: 1, veryBad: 0 },
    ourInvestment: 850,
    minDeposit: 10,
    maxDeposit: 50000,
    roi: 2.2,
    duration: '2.2% Daily Forever',
    withdrawalType: 'Instant',
    referralPercent: '5% - 2%',
    lastPayoutDate: 'Today',
    startDate: '2026-06-18',
    monitoredDays: 80,
    monitorsCount: 9,
    ssl: 'Sectigo RSA Domain Validation Secure Server CA',
    hosting: 'OVH SAS Dedicated Server',
    processors: ['Bitcoin', 'USDT TRC20', 'Binance Pay', 'Dogecoin'],
    description: 'Multi-strategy AI trade execution on major derivatives exchanges.'
  },
  {
    id: 'proj_3',
    name: 'Vortex Capital Holdings',
    domain: 'vortex-holdings.biz',
    url: 'https://vortex-holdings.biz',
    logo: '/images/project3.png',
    status: 'PAYING',
    category: 'Class "A" (Top Performer)',
    rating: 4.7,
    reviewsCount: 64,
    votes: { excellent: 50, good: 10, average: 3, bad: 1, veryBad: 0 },
    ourInvestment: 600,
    minDeposit: 50,
    maxDeposit: 25000,
    roi: 4.0,
    duration: '4.0% Daily for 20 Business Days',
    withdrawalType: 'Instant',
    referralPercent: '6% - 3% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-07-28',
    monitoredDays: 40,
    monitorsCount: 7,
    ssl: 'Let\'s Encrypt Authority X3',
    hosting: 'Cloudflare Inc.',
    processors: ['Bitcoin', 'Ethereum', 'USDT TRC20', 'Solana'],
    description: 'Energy infrastructure and green computing hardware leasing platform.'
  },
  {
    id: 'proj_4',
    name: 'Solaris Energy Fund',
    domain: 'solaris-fund.cc',
    url: 'https://solaris-fund.cc',
    logo: '/images/project4.png',
    status: 'WAITING',
    category: 'Class "B" (Trial)',
    rating: 3.8,
    reviewsCount: 22,
    votes: { excellent: 10, good: 6, average: 4, bad: 2, veryBad: 0 },
    ourInvestment: 300,
    minDeposit: 20,
    maxDeposit: 10000,
    roi: 5.0,
    duration: '5% Daily for 15 Days',
    withdrawalType: 'Manual (up to 12h)',
    referralPercent: '4%',
    lastPayoutDate: 'Yesterday',
    startDate: '2026-08-25',
    monitoredDays: 12,
    monitorsCount: 4,
    ssl: 'cPanel Inc CA',
    hosting: 'Namecheap Hosting Inc.',
    processors: ['USDT TRC20', 'Tron', 'Litecoin'],
    description: 'Renewable microgrid financing with automated smart contracts.'
  },
  {
    id: 'proj_5',
    name: 'Crypto Vault Apex',
    domain: 'apexvault.finance',
    url: 'https://apexvault.finance',
    logo: '/images/project5.png',
    status: 'PAYING',
    category: 'Class "Premium" (TOP Choices)',
    rating: 4.9,
    reviewsCount: 198,
    votes: { excellent: 175, good: 18, average: 4, bad: 1, veryBad: 0 },
    ourInvestment: 1500,
    minDeposit: 100,
    maxDeposit: 250000,
    roi: 1.8,
    duration: '1.8% - 3.2% Daily Tiered Returns',
    withdrawalType: 'Instant',
    referralPercent: '8% - 3% - 2% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-05-12',
    monitoredDays: 117,
    monitorsCount: 18,
    ssl: 'DigiCert Global Root CA',
    hosting: 'Amazon Web Services (AWS)',
    processors: ['Bitcoin', 'Ethereum', 'USDT TRC20', 'USDC', 'BNB', 'Cardano'],
    description: 'Cross-chain staking derivatives and automated market making liquidity aggregator.'
  },
  {
    id: 'proj_6',
    name: 'Aetheria Deep Trade',
    domain: 'aetheria-trade.com',
    url: 'https://aetheria-trade.com',
    logo: '/images/project6.png',
    status: 'NEW',
    category: 'New Listing',
    rating: 4.2,
    reviewsCount: 8,
    votes: { excellent: 6, good: 2, average: 0, bad: 0, veryBad: 0 },
    ourInvestment: 250,
    minDeposit: 15,
    maxDeposit: 5000,
    roi: 6.0,
    duration: '6.0% Daily for 10 Days',
    withdrawalType: 'Instant',
    referralPercent: '5% - 1%',
    lastPayoutDate: 'Today',
    startDate: '2026-09-02',
    monitoredDays: 4,
    monitorsCount: 2,
    ssl: 'Cloudflare Inc ECC CA-3',
    hosting: 'Cloudflare',
    processors: ['USDT TRC20', 'Bitcoin', 'Litecoin'],
    description: 'Fresh quantitative neural network arbitrage system recently added to monitoring.'
  },
  {
    id: 'proj_7',
    name: 'Horizon Peak Estates',
    domain: 'horizonpeak-asset.org',
    url: 'https://horizonpeak-asset.org',
    logo: '/images/project7.png',
    status: 'PROBLEM',
    category: 'Not Paying / Scam',
    rating: 2.1,
    reviewsCount: 54,
    votes: { excellent: 4, good: 2, average: 8, bad: 25, veryBad: 15 },
    ourInvestment: 500,
    minDeposit: 50,
    maxDeposit: 20000,
    roi: 3.0,
    duration: '3.0% Daily for 25 Days',
    withdrawalType: 'Pending (Delayed > 48h)',
    referralPercent: '5%',
    lastPayoutDate: 'Aug 24, 2026',
    startDate: '2026-07-01',
    monitoredDays: 67,
    monitorsCount: 6,
    ssl: 'Let\'s Encrypt',
    hosting: 'Shared Web Host',
    processors: ['Bitcoin', 'USDT TRC20'],
    description: 'WARNING: Withdrawals reported pending past advertised timeframe. Do not deposit.'
  },
  {
    id: 'proj_8',
    name: 'Terra Nova Minerals',
    domain: 'terranova-mining.ltd',
    url: 'https://terranova-mining.ltd',
    logo: '/images/project8.png',
    status: 'SCAM',
    category: 'Not Paying / Scam',
    rating: 1.2,
    reviewsCount: 112,
    votes: { excellent: 1, good: 1, average: 3, bad: 42, veryBad: 65 },
    ourInvestment: 400,
    minDeposit: 25,
    maxDeposit: 15000,
    roi: 8.0,
    duration: '8.0% Daily for 7 Days',
    withdrawalType: 'Stopped / Site Error',
    referralPercent: '10%',
    lastPayoutDate: 'Aug 14, 2026',
    startDate: '2026-06-25',
    monitoredDays: 73,
    monitorsCount: 8,
    ssl: 'Expired / Self-Signed',
    hosting: 'Offline / Suspended',
    processors: ['Bitcoin', 'USDT TRC20'],
    description: 'SCAM CONFIRMED. Selective payouts reported. Administrator unresponsive.'
  }
];

export const fallbackStats = {
  totalMonitored: 13,
  payingCount: 9,
  totalInvested: 16800,
  totalPayouts: 34219.50,
  insurancePool: 75000,
  activeVisitors: 14289
};
